---
config:
  - name: total_runtime_minutes
    description: The amount of runtime each forecast takes, in minutes.
    type: gauge
    sequence:
      - eval_time: 1
        interval: 5
        median: 60
        standard_deviation: 7.5
        minimum: 0
        maximum: 120
  - name: I_O_Fraction_percent
    description: The ratio of time spent in input to time spent in output.
    type: gauge
    sequence:
      - eval_time: 1
        interval: 5
        median: 10
        standard_deviation: 3
        minimum: 0
        maximum: 100
  - name: Initial_RMS_pressure_tendency
    description: The initial RMS pressure tendency.
    type: gauge
    sequence:
      - eval_time: 1
        interval: 5
        median: 0.8
        standard_deviation: 0.1
        minimum: 0
        maximum: 2
historical_range_hours: 720
interval_hours: 6
starting_hour: 0
real_time_mode: True
