global:
  scrape_interval: 10s

scrape_configs:
  - job_name: prometheus-data-generator
    static_configs:
      - targets: ['docker.for.mac.localhost:9000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['docker.for.mac.localhost:9090']